config_data:
  task: cookieTheft
  transcript_version: google
config_audio_features:
  feature_version: reduced  # reduced set of features - without too strong correlations
config_linguistic_features:
  feature_version: reduced  # reduced set of features - without too strong correlations
config_model:
  model_name: SVR
  target_variable: composite_language
  calculate_shap: true
debug: false
model: Regression
data_transformers:
- Linguistic Features
- Audio Features
- Demographic Features
data_preprocessors:
- Outlier Removal and Imputation
- Feature Standardizer
